version: "3.8"

services:
  share-net:
    build: .
    image: thelostlambda/share-net:latest
    network_mode: "host"
    environment:
      link: enp0s31f6 
      wanlink: wlp4s0
    privileged: true
    cap_add:
      - NET_ADMIN
